### PR TITLE
Update clap to v4

### PR DESCRIPTION
**Pull request by kdnakt**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by rejao — APPROVED** [review]
lgtm

**Review by rejao — CHANGES_REQUESTED** [review]
Can you please bump the package version

**Comment by kdnakt** [comment]
> Can you please bump the package version

Sure!
Before modifying the Cargo.toml file, please allow me to confirm two points:

1. Should the next version be 0.3.3, or would 0.4.0 be more appropriate?
2. Should I add this information to the CHANGELOG.md? I couldn't determine if it qualifies as notable changes.

**Comment by vche** [comment]
Thanks ! But don't bother. We have another pending merge, so we have updated the revision there. We're merging this now and will publish a new releast in cargo today :)

**Pull request merged**
