### PR TITLE
File input

### LINKED ISSUE #20: File input
I may have missed it, but I didn't find in the docs how to get input from a log file.

It would need to:
* Not read the whole file from the start, but seek to the end and read from there (like `tail -f`)
* Keep working if a logrotate service renames the log file and creates a new file with the previous name (flowgger should start reading the new file).

### PR DESCRIPTION
**Pull request by Trojan295**
Fixes #20.

The file input:
- supports tail-like reading for existing files and dynamic recognition of new files (via inotify)
- handles multiple file inputs (src path can be glob compatible string with wildcards)

### CODE REVIEW

**Comment by Trojan295** [comment]
I see, that the CI is failing on FreeBSD, because of inotify, which is a Linux kernel feature.

Looks it can be tricky to support Linux and FreeBSD.

**Comment by jedisct1** [comment]
Errr.. yes, don't break portability please...

**Comment by jedisct1** [comment]
Maybe use https://github.com/passcod/notify ?

**Comment by Trojan295** [comment]
This passcod/notify looks promising!

**Comment by Trojan295** [comment]
There is some problem with passcod/notify also. I created a issue there https://github.com/passcod/notify/issues/155. I would say this PR is put on hold, till notify v5 is released.

**Comment by mirwan** [comment]
@Trojan295 
Any update on this one? seems like https://github.com/passcod/notify/issues/155 is closed

**Comment by Trojan295** [comment]
Ok, CI is green, so I believe it can be reviewed. @jedisct1

**Comment by crisidev** [comment]
We merged this PR with small changes during the transition to awslabs. Closing.

**Pull request closed without merging**
