### PR TITLE
Update capnp to 0.10

### PR DESCRIPTION
**Pull request by Trojan295**
*Issue #, if available:* part of #33

*Description of changes:*
This PR updates the capnp library to 0.10. As a result the capnp schema was recompiled. I couldn't find a flag to tell the capnp compiler to put the sources in a specific package path (now it is `crate::flowgger::capnp_record`, in my PR it's under `crate::capnp_record`), so I moved the compiled schema to the crate root.

@jedisct1 , is there some way to change that, besides modifying the generated schema manually?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jedisct1** [comment]
There has to be a way, but off the top of my head, I don't know :)

Not a big deal.

**Comment by kurojishi** [comment]
Can i ask you to write some tests for this before merging it in? I don't know this module enough to say this work as intended without tests

**Comment by Trojan295** [comment]
I'm gonna write the tests next week

**Comment by Trojan295** [comment]
@kurojishi, I added some tests

**Comment by vche** [comment]
Thanks @Trojan295 ! Looks good to me

**Review by vche — APPROVED** [review]

**Review by kurojishi — APPROVED** [review]
Great, approved, and merged

**Pull request merged**
