### PR TITLE
fix: warn when cargo clippy

### PR DESCRIPTION
**Pull request by DaviRain-Su**
*Issue #, if available:*

*Description of changes:*

fix: warn when cargo clippy, and fix some code.

### CODE REVIEW

**Comment by vche** [comment]
Thanks for your contribution. The tests seem to fail due to a missing package though. Can you check that ?

**Comment by DaviRain-Su** [comment]
> Thanks for your contribution. The tests seem to fail due to a missing package though. Can you check that ?

Ok, This test seem before have already build error.

**Comment by DaviRain-Su** [comment]
> Thanks for your contribution. The tests seem to fail due to a missing package though. Can you check that ?

I have find some solution, but I can't setting configuation, https://github.com/rust-embedded/cross/issues/404. Can you help me.

**Comment by vche** [comment]
Of course. I will take look later today or tomorrow.

**Comment by DaviRain-Su** [comment]
> Of course. I will take look later today or tomorrow.

ye, thx.

**Comment by vche** [comment]
Thanks for your patience. Just a quick update here, openssl is indeed missing in the arm platforms, and was before your pull request.

I am working on it, and will fix it, but I am struggling finding enough time to deal with this at the moment. Let me know if you that is blocking you.

**Comment by DaviRain-Su** [comment]
> Thanks for your patience. Just a quick update here, openssl is indeed missing in the arm platforms, and was before your pull request.
> 
> I am working on it, and will fix it, but I am struggling finding enough time to deal with this at the moment. Let me know if you that is blocking you.

Thx, I'm ok.

**Pull request closed without merging**
